### ISSUE TITLE
No file for Unilmv2

### ISSUE THREAD

**Issue by dmhyun** [yflyl613/Tiny-NewsRec#1]
Hello,

I got the below error when I run 'Domian-specific_Post-train.ipynb'. I think the file for unilmv2 is missing in the current repository. Please let me know the solution to the problem. Thanks in advance.

![image](https://user-images.githubusercontent.com/7232862/212889714-7fe777e6-9064-436e-a78a-295cfaf5df1d.png)

**Comment by yflyl613** [comment]
> Hello,
> 
> I got the below error when I run 'Domian-specific_Post-train.ipynb'. I think the file for unilmv2 is missing in the current repository. Please let me know the solution to the problem. Thanks in advance.
> 
> ![image](https://user-images.githubusercontent.com/7232862/212889714-7fe777e6-9064-436e-a78a-295cfaf5df1d.png)

I'm sorry I could not provide the UniLM-v2 model used in our experiments. As far as I know, the authors of UniLM-v2 haven't publicized the pre-trained model so far. I luckily have access to the model during my internship at Microsoft. You may check their [official repo](https://github.com/microsoft/unilm) to see whether a public pre-trained model is available now. Otherwise, you can use other pre-trained language models instead, such as BERT or RoBERTa.

**Comment by dmhyun** [comment]
Thanks for your reply! I will try other models.
